[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "firefly_client_py"
version = "1.0.0"
description = "Library to interact with firefly api gateway"
readme = "README.md"